[profile.default]
src = "src"
out = "out"
libs = ["lib"]
network = "monad"

# Monad Testnet Configuration
eth-rpc-url = "https://testnet-rpc.monad.xyz"
chain_id = 10143

# Remappings (voir remappings.txt) — nécessite `forge install OpenZeppelin/openzeppelin-contracts`
